[package]
name = "rpfm_ui"
version = "1.6.2"
build = "build.rs"
authors = ["Frodo45127 <frodo_gv@hotmail.com>"]
description = "A modding tool for Total War games."
edition = "2018"

[dependencies]
# Internal dependencies.
rpfm_error = { path = "../rpfm_error" }
rpfm_lib = { path = "../rpfm_lib" }

# Config dependencies.
lazy_static = "^1.2"

# Serialization dependencies.
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"

# Date conversion support.
chrono = "^0.4"

# Support for checking/downloading schemas.
restson = "^0.5"
reqwest = "^0.9"

# Support for Regex operations.
regex = "^1"

# Support for open files in a native way.
open = "^1.2"

# Qt dependencies.
cpp_utils = "^0.2"
qt_core = "^0.2"
qt_gui = "^0.2"
qt_widgets = "^0.2"

# Support for formatting math operations.
meval = "^0.2"

# Windows resources support.
[target.'cfg(windows)'.build-dependencies]
winres = "^0.1"

[profile.release]
lto = true
debug = true
