strategy:
  matrix:
    stable:
      rustup_toolchain: stable

pool:
  vmImage: 'ubuntu-16.04'

steps:
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUSTUP_TOOLCHAIN
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: Install Rust

  - script: |
      wget https://download.qt.io/archive/qt/5.13/5.13.0/qt-opensource-linux-x64-5.13.0.run
      chmod +x qt-opensource-linux-x64-5.13.0.run
    displayName: Install Qt5

  - script: |
      sudo apt install xz-utils p7zip-full
    displayName: Install Compression Utilities

  - script: cargo build --all
    displayName: Cargo build

  - script: cargo test --all
    displayName: Cargo test