[book]
authors = ["Ismael Gutiérrez González"]
multilingual = false
src = "./docs_src"
title = "Rusted PackFile Manager Documentation"

[build]
build-dir = "./docs"

[output.html]
default-theme = "rust"