[package]
name = "rpfm-code"
version = "0.0.4"
authors = ["Frodo45127 <frodo_gv@hotmail.com>"]
build = "build.rs"

[dependencies]
byteorder = "1.1.0"
num = "0.1.40"
csv = "1.0.0-beta.5"
serde = "1.0.20"
serde_derive = "1.0.20"

[dependencies.gtk]
version = "0.2.0"
features = ["v3_22"]

[dependencies.gdk]
version = "0.6.0"

[target.x86_64-pc-windows-gnu.build-dependencies]
winres = "0.1"

[profile.release]
lto = true
