[package]
name = "rpfm-code"
version = "0.8.1"
authors = ["Frodo45127 <frodo_gv@hotmail.com>"]
build = "build.rs"
description = "A modding tool for Total War games."

[dependencies]
byteorder = "1.2"
encoding = "0.2.33"
num = "0.1"
csv = "1.0.0-beta.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde-xml-rs = "0.2"
chrono = "0.4"
failure = "0.1"
uuid = { version = "0.6", features = ["v4"] }
restson = "0.2"
url = "1.7"
futures = "0.1"
hyper = "0.11"
hyper-tls = "0.1"
tokio-core = "0.1"

gtk = { version = "0.4.0", features = ["v3_22", "embed-lgpl-docs"] }
gdk = "0.8.0"
gdk-pixbuf = "0.4.0"
gio = "0.4.0"
glib = "0.5.0"
pango = "0.4.0"
sourceview = "0.4.0"

[target.x86_64-pc-windows-gnu.build-dependencies]
winres = "0.1.5"

[profile.release]
lto = true
