[package]
name = "rpfm-code"
version = "0.4.1"
authors = ["Frodo45127 <frodo_gv@hotmail.com>"]
build = "build.rs"
description = "A modder tool for Total War: Warhammer 2."

[dependencies]
byteorder = "1.1.0"
num = "0.1.40"
csv = "1.0.0-beta.5"
serde = "1.0.20"
serde_derive = "1.0.20"
serde_json = "1.0"
serde-xml-rs = "0.2"
unescape = "0.1.0"
hex-slice = "0.1.2"
chrono="0.4.0"
failure="0.1"

[dependencies.gtk]
version = "0.3.0"
features = ["v3_22"]

[dependencies.gdk]
version = "0.7.0"

[dependencies.glib]
version = "0.4.0"

[dependencies.gio]
version = "*"

[dependencies.sourceview]
version = "0.3.0"

[target.x86_64-pc-windows-gnu.build-dependencies]
winres = "0.1.5"

[profile.release]
lto = true
