[package]
name = "rpfm-code"
version = "0.6.0"
authors = ["Frodo45127 <frodo_gv@hotmail.com>"]
build = "build.rs"
description = "A modding tool for Total War games."

[dependencies]
byteorder = "1.1.0"
num = "0.1.40"
csv = "1.0.0-beta.5"
serde = "1.0.20"
serde_derive = "1.0.20"
serde_json = "1.0"
serde-xml-rs = "0.2"
hex-slice = "0.1.2"
chrono = "0.4.0"
failure = "0.1"
uuid = { version = "0.6", features = ["v4"] }
restson = "0.1.3"

[dependencies.gtk]
version = "0.3.0"
features = ["v3_22", "embed-lgpl-docs"]

[dependencies.gdk]
version = "0.7.0"

[dependencies.glib]
version = "0.4.0"

[dependencies.gio]
version = "0.3.0"

[dependencies.pango]
version = "0.3.0"

[dependencies.sourceview]
version = "0.3.0"

[target.x86_64-pc-windows-gnu.build-dependencies]
winres = "0.1.5"

[profile.release]
lto = true
