[package]
name = "rpfm-code"
version = "0.9.3"
authors = ["Frodo45127 <frodo_gv@hotmail.com>"]
build = "build.rs"
description = "A modding tool for Total War games."

[dependencies]
byteorder = "1.2"
encoding = "0.2.33"
num = "0.2"
csv = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde-xml-rs = "0.2"
chrono = "0.4"
failure = "0.1"
uuid = { version = "0.6", features = ["v4"] }
restson = "0.3"
futures = "0.1"
hyper = "0.11"
hyper-tls = "0.1"
tokio-core = "0.1"

sentry = "0.7"

qt_widgets = "0.2"
qt_gui = "0.2"
qt_core = "0.2"

cpp_utils = "*"

[target.x86_64-pc-windows-gnu.build-dependencies]
winres = "0.1.5"

[profile.release]
lto = true
debug = true
