[package]
name = "rpfm-code"
version = "1.3.3"
authors = ["Frodo45127 <frodo_gv@hotmail.com>"]
build = "build.rs"
description = "A modding tool for Total War games."
edition = "2018"

[dependencies]
byteorder = "1.2"
encoding = "0.2.33"
num = "0.2"
csv = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde-xml-rs = "0.2"
chrono = "0.4"
failure = "0.1"
uuid = { version = "0.6", features = ["v4"] }
restson = "0.4"
reqwest = "0.9"
open = "*"
indexmap = "1.0"
regex = "1"

sentry = "0.12"

qt_core = "0.2"
qt_gui = "0.2"
qt_widgets = "0.2"

cpp_utils = "*"
lazy_static = "*"
os_info = "1.1.0"
toml = "0.4.7"

bitflags = "1.0"
[target.'cfg(windows)'.build-dependencies]
winres = "0.1.5"

[profile.release]
lto = true
debug = true
