[package]
name = "rpfm_cli"
version = "1.6.2"
authors = ["Frodo45127 <frodo_gv@hotmail.com>"]
description = "A CLI tool to automate all your modding needs."
edition = "2018"

[dependencies]
# Internal dependencies.
rpfm_error = { path = "../rpfm_error" }
rpfm_lib = { path = "../rpfm_lib" }

# CLI parsing, formatting and color support.
clap = "^2.33"
colored = "1.8.0"
prettytable-rs = "0.8.0"
bytesize = "1.0.0"

# Logging support.
log = "^0.4"
simplelog = "^0.6.0"
simple_logger = "^1.0"

[profile.release]
lto = true
debug = true
